### ISSUE TITLE
investigate unit test **test_call_link_sub_ecdsa** from *enclave-runtime/src/test*

### ISSUE THREAD

**Issue by BillyWooo** [litentry/tee-worker#15]
Unit test **test_call_link_sub_ecdsa** is disabled for the moment. Because of the updating to upstream (bbcf62e7), the unit test doesn't pass any more. As there are dependencies on this updating (polkadot-v0.9.26), the test is disabled. 

Investigate/fix this unit test.

**Comment by BillyWooo** [comment]
## Revers investigation
From **tee-worker**, commit hash <af50768e00b9e4794b74824d3a6f2e12092dd6d3>, **test_call_link_sub_ecdsa** can not pass anymore. Dig in the [diff](https://github.com/litentry/tee-worker/compare/39a08fbb...af50768e), all possible relative information comes from [here](https://github.com/litentry/tee-worker/compare/39a08fbb...af50768e#diff-c444070529ce25a5489854de691d0ad4dd014d6b84f86cfc9e5105fbb5e07f4fL59-L105), i.e. *sgx_runtime* -> *ita_sgx_runtime*.  But **SgxAccountLinkerCall** comes from **pallet-sgx-account-linker**, from [here](SgxAccountLinkerCall) and [here](https://github.com/litentry/tee-worker/compare/39a08fbb...af50768e#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87eL7558-L7560). So finally end up with [litentry/sgx-runtime](https://github.com/litentry/sgx-runtime/compare/0c5ebe3122a6356fcc27fad05693182742342211...8cf5b0dbdf45108f3573fcc6e5b64f71aa9304b3). The possible change is [polkadot update](https://github.com/litentry/sgx-runtime/compare/0c5ebe3122a6356fcc27fad05693182742342211...8cf5b0dbdf45108f3573fcc6e5b64f71aa9304b3#diff-c751655c35ebdf4e4b6687298ac626e5981668171532cf8639245784ade772c3L21-R26). Maybe that's the cause.

## From the current test result
The [hard code](https://github.com/litentry/tee-worker/blob/dev/enclave-runtime/src/test/tests_main.rs#L846-L862) leads to test failure. Direct root cause is: hard code of **signature** is wrong.
```
[2022-08-30T13:18:06Z ERROR pallet_sgx_account_linker::pallet] public_key: [1, 229, 82, 41, 142, 71, 69, 64, 65, 234, 49, 39, 59, 75, 99, 12, 100, 193, 4, 228, 81, 74, 163, 100, 52, 144, 184, 170, 202, 156, 248, 237], hashed_pk: [216, 144, 140, 22, 93, 238, 120, 89, 36, 231, 66, 26, 15, 208, 65, 138, 25, 213, 218, 238, 195, 149, 253, 80, 90, 146, 160, 253, 49, 23, 228, 40]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Dispatch("Module(ModuleError { index: 6, error: [7, 0, 0, 0], message: Some(\"WrongSignature\") })")', src/test/tests_main.rs:876:71
testing test_call_link_sub_ecdsa ... failed!

failures:     
    test_call_link_sub_ecdsa

test result FAILED. 66 tested, 65 passed, 1 failed
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Sgx(SGX_ERROR_UNEXPECTED)', service/src/tests/mod.rs:42:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## conclusion
I think it's not valuable to spend extra time here based on the following reason:
- Either directly update the hardcode, which is only to pass the test.
- Short discussion with Kai, this part of code will be anyway removed in the future.

What's your opinion? @StamfordDigital  @Kailai-Wang  ?

**Comment by BillyWooo** [comment]
As discussed in today's daily, we decided to stop here for the moment.
